# Generated by Django 3.2.8 on 2021-12-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_template_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'managed': True, 'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
    ]
