# Generated by Django 3.2.8 on 2021-12-27 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_template_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.template')),
            ],
            options={
                'verbose_name': 'Directive',
                'verbose_name_plural': 'Directives',
                'managed': True,
            },
        ),
    ]
