# Generated by Django 3.2.8 on 2021-12-27 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0005_directive'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.template')),
            ],
            options={
                'verbose_name': 'SignatueDoc',
                'verbose_name_plural': 'SignatueDocs',
                'managed': True,
            },
        ),
    ]
