# Generated by Django 3.2.8 on 2021-12-27 11:10

from django.db import migrations, models
import work.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20211227_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturedocx',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=work.models.content_file_name, verbose_name='Подписанный докумет'),
        ),
    ]
