# Generated by Django 3.2.8 on 2022-01-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_signaturedocx_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturedocx',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='signatured/', verbose_name='Подписанный докумет'),
        ),
    ]
