# Generated by Django 3.2.8 on 2022-01-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_alter_signaturedocx_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_exist',
            field=models.BooleanField(default=True, verbose_name='удаление'),
            preserve_default=False,
        ),
    ]
