# Generated by Django 3.2.8 on 2022-02-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_systemdirective'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemdirective',
            name='default_value',
            field=models.TextField(blank=True, default='', verbose_name='Значение подставляющиеся автоматически'),
        ),
        migrations.AlterField(
            model_name='systemdirective',
            name='desc',
            field=models.TextField(verbose_name='Описание которое увидят пользователи'),
        ),
        migrations.AlterField(
            model_name='systemdirective',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название которое увидят пользователи'),
        ),
    ]
