# Generated by Django 3.2.8 on 2021-12-25 14:55

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('date_burn', models.DateField(blank=True, verbose_name='birthday')),
                ('pasport', models.CharField(blank=True, max_length=20, verbose_name="pasport's seria and number")),
                ('pasport_otdel', models.CharField(blank=True, max_length=250, verbose_name='who gives pasport')),
                ('pasport_code', models.CharField(blank=True, max_length=50, verbose_name='code')),
                ('date_pasport', models.DateField(blank=True, verbose_name='pasport date')),
                ('registr', models.TextField(blank=True, verbose_name='from')),
                ('organisation', models.CharField(blank=True, max_length=200, verbose_name='full organisation name')),
                ('inn', models.CharField(blank=True, max_length=100)),
                ('ogrn', models.CharField(blank=True, max_length=100)),
                ('name_bank', models.CharField(blank=True, max_length=100)),
                ('bik', models.CharField(blank=True, max_length=100)),
                ('schet', models.CharField(blank=True, max_length=100)),
                ('korp_schet', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
