# Generated by Django 3.2.8 on 2021-12-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bik',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_burn',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_pasport',
            field=models.DateField(blank=True, null=True, verbose_name='pasport date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='korp_schet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name_bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ogrn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='full organisation name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pasport',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="pasport's seria and number"),
        ),
        migrations.AlterField(
            model_name='user',
            name='pasport_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pasport_otdel',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='who gives pasport'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registr',
            field=models.TextField(blank=True, null=True, verbose_name='from'),
        ),
        migrations.AlterField(
            model_name='user',
            name='schet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
