# Generated by Django 3.2.8 on 2021-12-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211225_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pasport_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='pasport code'),
        ),
    ]
