# Generated by Django 3.2.8 on 2022-01-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verEmail',
            field=models.BooleanField(default=False, verbose_name='Верификация email'),
            preserve_default=False,
        ),
    ]
