# Generated by Django 3.2.8 on 2022-01-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_veremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verEmail',
            field=models.BooleanField(blank=True, null=True, verbose_name='Верификация email'),
        ),
    ]
